FanVers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('Advertisement/', include(('Advertisement.urls', 'Advertisement'), namespace='Advertisement')),
    path('ckeditor/', include('ckeditor_uploader.urls')), #текстовый редактор CKEditor
    re_path(r'^public/(?P<path>.*)$', serve, {'document_root': settings.BASE_DIR / 'public'}), #временное отображение папки public

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "main.views.page_not_found_view"

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('For-copyright-holders/', views.For_copyright_holders, name='For_copyright_holders'),
    path('user-agreement/', views.user_agreement, name='user_agreement'),
    path('Reference/', views.Reference, name='Reference'),
    path('Write-to-support/', views.Write_to_support, name='Write_to_support'),
    path('Contacts/', views.Contacts, name='Contacts'),
    path('money_problem/', views.money_problem, name='money_problem'),
    path('Suggest_improvements/', views.Suggest_improvements, name='Suggest_improvements'),
    path('thanks/', views.thanks, name='thanks'),
    path('FAQ/', views.faq, name='faq'),
    path("__debug__/", include("debug_toolbar.urls")),
]

handler404 = "main.views.page_not_found_view"

main/models.py
from django.db import models

class Settings(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from catalog.models import Book
from .models import Settings
from Advertisement.models import *
from Advertisement.views import del_adv
from catalog.serializers import BookSerializer
from django.views.generic import ListView, TemplateView
from datetime import date, timedelta
from django.utils import timezone
from django.db.models import Count

class HomePageView(ListView):
    model = Book
    serializer_class = BookSerializer
    template_name = 'main/index.html'

    def adv_show(self):
        del_adv()
        adv = Advertisement.objects.filter(location='main')
        adv_books = list()
        for book in adv:
            adv_books.append(book.book_id)

        adv_books = Book.objects.filter(id__in=adv_books)

        return adv_books

    def new_books(self):
        end_of_month = timezone.now()
        start_of_month = end_of_month - timezone.timedelta(days=30)
        new_books = Book.objects.filter(
        pub_date__range=(start_of_month, end_of_month)
        ).order_by('-pub_date')[:8]
        return new_books

    def last_updated_books(self):
        end_of_month = timezone.now()
        start_of_month = end_of_month - timezone.timedelta(days=30)
        last_updated_books = Book.objects.filter(
        book_chapters__created_at__range=(start_of_month, end_of_month)
        ).distinct().order_by('-book_chapters__created_at')[:6]
        return last_updated_books

    def trending_books(self):
        trending_books = Book.objects.order_by('-trending_score')[:6]
        return trending_books

    def top_day_books(self):
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=1)

        top_day_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_day_books

    def top_week_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=7)

        top_week_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_week_books

    def top_month_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=30)

        top_month_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_month_books

    def top_general_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=365)

        top_general_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_general_books



def For_copyright_holders(request):
    return render(request, 'main/For_copyright_holders.html')

def Reference(request):
    return render(request, 'main/Reference.html')

def Write_to_support(request):
    return render(request, 'main/Write_to_support.html')
def Contacts(request):
    return render(request, 'main/Contacts.html')

def thanks(request):
    return render(request, 'main/thanks.html')

def Suggest_improvements(request):
    return render(request, 'main/Suggest_improvements.html')

def money_problem(request):
    return render(request, 'main/money_problem.html')
def user_agreement(request):
    return render(request, 'main/user_agreement.html')

def faq(request):
    return render(request, 'main/faq.html')

def page_not_found_view(request, exception):
    return render(request, 'main/404.html', status=404)

main/templates/include/footer.html
{% load static %}
<footer>
  <div class="footer_wrapper">
    <a href="/">
      <div class="footer_logo">
        <img src="{% static 'main/images/assets/main-logo.png' %}"  alt="FanVers" width="150" height="150"/>
      </div>
    </a>
    <div class="footer_menu">
      <a href="{% url 'main:For_copyright_holders' %}">
        <p>Для правовласників</p>
      </a>
      <a href="{% url 'main:user_agreement' %}">
        <p>Угода користувача</p></a>
      <a href="{% url 'main:Reference' %}">
        <p>Довідка</p>
      </a>
      <a href="{% url 'main:money_problem' %}">
        <p>Не поповнився баланс?</p>
      </a>
    </div>
    <div class="footer_menu">
      <a href="{% url 'main:thanks' %}">
        <p>Сказати «дякую!»</p>
      </a>
      <a href="{% url 'main:Suggest_improvements' %}">
        <p>Запропонувати покращення</p>
      </a>
      <a href="{% url 'main:Contacts' %}">
        <p>Контакти</p>
      </a>
      <a href="{% url 'main:Write_to_support' %}">
        <p>Написати у підтримку</p>
      </a>
    </div>
    <div class="footer_socials">
      <a href="#">
        <img src="{% static 'main/images/assets/icons/facebook.svg' %}" alt="" />
      </a>
      <a href="#">
        <img src="{% static 'main/images/assets/icons/instagram.svg' %}" alt="" />
      </a>
    </div>
  </div>
  <div class="footer_bottom">
    <p>FanVers © 2023</p>
    <p>All rights reserved</p>
  </div>
</footer>

main/templates/include/show_more.html
<button class="about_book_action show_more">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
  >
    <path d="M14 15L10 19L14 23" stroke="white" />
    <path
      d="M5.93782 15.5C5.14475 14.1264 4.84171 12.5241 5.07833 10.9557C5.31495 9.38734 6.07722 7.94581 7.24024 6.86729C8.40327 5.78877 9.8981 5.13721 11.4798 5.01935C13.0616 4.90149 14.6365 5.32432 15.9465 6.21856C17.2565 7.1128 18.224 8.42544 18.6905 9.94144C19.1569 11.4574 19.0947 13.0869 18.5139 14.5629C17.9332 16.0389 16.8684 17.2739 15.494 18.0656C14.1196 18.8573 12.517 19.1588 10.9489 18.9206"
      stroke="white"
      stroke-linecap="round"
    />
  </svg>
  <p>Показати ще</p>
</button>

main/templates/include/sort.html
  <div class="translator_filter">
    <span>Сортувати за</span>

  <form action="" method="get" id="sortform">
      <input type="hidden" id="orderval" value="{{order}}">
      {% for book in books %}
      <input type="hidden" name="bookid" id="bookid" value="{{book.id}}">
      {% endfor %}

    <select name="order" id="order" onchange="sendSort()">
      <option id="title" value="title">назвою</option>
      <option id="pub_date" value="pub_date">датою створення</option>
      <option id="last_updated" value="last_updated">датою оновлення</option>
      <option id="ratings" value="ratings">рейтингом твору</option>
      <option id="views" value="views">переглядами</option>
      <option id="quality" value="quality">якістю перекладу</option>
      <option id="free_pages" value="free_pages">кількістю безкоштовних сторінок</option>
      <option id="pages" value="pages">кількістю сторінок</option>
      <option id="chapters" value="chapters">кількістю розділів</option>
      <option id="bookmarks_sort" value="bookmarks_sort">кількістю в закладках</option>
    </select>

  </form>
  </div>
<script>
  function sendSort() {
    var form = document.getElementById('sortform');
    form.submit();
  };

  $(document).ready(function () {
    var sel = document.getElementById('orderval');
    var opt = document.getElementById(sel.value)
    $('#'+sel.value).attr("selected", "selected");
  });
</script>