FanVers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('Advertisement/', include(('Advertisement.urls', 'Advertisement'), namespace='Advertisement')),
    path('ckeditor/', include('ckeditor_uploader.urls')), #текстовый редактор CKEditor
    re_path(r'^public/(?P<path>.*)$', serve, {'document_root': settings.BASE_DIR / 'public'}), #временное отображение папки public

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "main.views.page_not_found_view"

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('For-copyright-holders/', views.For_copyright_holders, name='For_copyright_holders'),
    path('user-agreement/', views.user_agreement, name='user_agreement'),
    path('Reference/', views.Reference, name='Reference'),
    path('Write-to-support/', views.Write_to_support, name='Write_to_support'),
    path('Contacts/', views.Contacts, name='Contacts'),
    path('money_problem/', views.money_problem, name='money_problem'),
    path('Suggest_improvements/', views.Suggest_improvements, name='Suggest_improvements'),
    path('thanks/', views.thanks, name='thanks'),
    path('FAQ/', views.faq, name='faq'),
    path("__debug__/", include("debug_toolbar.urls")),
]

handler404 = "main.views.page_not_found_view"

users/urls.py
from django.urls import path, include
from .views import login_modal_view, signup_modal_view, logout_view, ProfileDetail, ProfileUpdate
from . import views
from .dialogs import get_or_create_dialog
from rest_framework_simplejwt.views import TokenObtainPairView

app_name = 'users'


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('login_modal/', login_modal_view, name='login_modal'),
    path('signup_modal/', signup_modal_view, name='signup_modal'),
    path('logout/', logout_view, name='logout'),
    path('profile/', ProfileDetail.as_view(), name='profile'),
    path('profile/detail/<str:username>/', views.OtherUserProfileDetail.as_view(), name='other_profile_detail'),
    path('profile/list/', views.ProfileListView.as_view(), name='translators'),
    path('edit-account/', ProfileUpdate.as_view(), name='ProfileUpdate'),
    path('purchase-chapter/<int:chapter_id>/', views.purchase_chapter, name='purchase_chapter'),
    path('add_funds/', views.add_funds, name='add_funds'),
    path('users/purchase-chapter/<int:chapter_id>/', views.purchase_chapter, name='purchase_chapter'),
    path('commission-stats/', views.commission_stats, name='commission_stats'),
    path('dialogs/', views.dialogs_list, name='dialogs_list'),
    path('dialog/<int:dialog_id>/', views.dialog_view, name='dialog_view'),
    path('dialog/create/', views.create_dialog, name='create_dialog'),
    path('user/<str:username>/dialog/', views.create_dialog, name='create_dialog'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('save-token/', views.save_token, name='save_token'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Message
from django.forms import ModelForm, FileInput

class CreationUserForm(UserCreationForm):
    # class Meta:
    #     model = User
    #     fields = ['username', 'email', 'password1', 'password2']
    #     labels = {
    #         'username': 'Логін',
    #         'email': 'Email',
    #         'password1': 'Пароль',
    #         'password2': 'Підтвердження пароля'
    #     }

    username = forms.CharField(label='Логін')
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Підтвердження пароля', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(CreationUserForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control input-box form-ensurance-header-control'})


class LoginForm(forms.Form):
    username = forms.CharField(label='Логін')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control input-box form-ensurance-header-control'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['username', 'email',
                  'about', 'image',
                  ]
        labels = {
            'username': 'Логін',
            'email': 'Email',
            'about': 'Детально про себе',
            'image': 'Змінити фото профілю',
        }
        widgets = {
            'image': FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control input-box form-ensurance-header-control'})



class AddFundsForm(forms.Form):
    amount = forms.DecimalField()

class PurchaseChapterForm(forms.Form):
    chapter_id = forms.IntegerField()


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']


class RegistrationForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

users/views.py
from django.http import JsonResponse, HttpResponse
from .forms import CreationUserForm, LoginForm, AddFundsForm, PurchaseChapterForm, MessageForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, Transaction, Message
from .forms import ProfileForm, MessageForm
from django.urls import reverse_lazy
from django.contrib.auth.models import Group, User
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.db import transaction
from catalog.models import Chapter, Book, Comment, Rating
from decimal import Decimal
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, View
from django.http import Http404
from .models import Dialog
from .dialogs import get_or_create_dialog
from django.db.models import Q, Count, Avg, Sum, Case, When, IntegerField
from rest_framework_simplejwt.views import TokenObtainPairView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def save_token(request):
    if request.method == 'POST':
        token = request.POST.get('token')
        user = request.user  # Получите текущего аутентифицированного пользователя

        if user and token:

            # Сохраните токен в базе данных
            user.profile.token = token  # Предполагается, что у пользователя есть профиль с полем "token"
            user.profile.save()

            return JsonResponse({'message': 'Токен успешно сохранен'})
        else:
            return JsonResponse({'message': 'Ошибка: недопустимый токен или пользователь'}, status=400)

    return JsonResponse({'message': 'Ошибка: неверный метод запроса'}, status=400)



def login_modal_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                # Создание экземпляра TokenObtainPairView и получение токена
                token_obtain_pair_view = TokenObtainPairView.as_view()
                response = token_obtain_pair_view(request)
                return response
            else:
                messages.error(request, 'Невірний Логін або Пароль')
                return JsonResponse({'success': False, 'errors': 'Невірний Логін або Пароль'}, status=400)
        else:
            errors = form.errors.as_json()
            return JsonResponse({'success': False, 'errors': errors}, status=400)
    else:
        form = LoginForm()
        return render(request, 'users/login_modal.html', {'form': form})


def logout_view(request):
    logout(request)

    response = redirect('main:home')
    response.delete_cookie('sessionid')
    return response


#  регистрация
def signup_modal_view(request):
    page = 'main:home'
    if request.method == 'POST':
        form = CreationUserForm(request.POST)
        if form.is_valid():
            user = form.save()

            user.is_active = True
            user.save()

            # Получаем группу 'Читач'
            reader_group = Group.objects.get(name='Читач')

            # Добавляем пользователя в группу 'Читач'
            user.groups.add(reader_group)

            # Обновляем профиль пользователя
            user.profile.group = user.groups.first()
            user.profile.save()

            # Авторизация пользователя
            login(request, user)
            # authenticate(request, username=user.username, password=user.password)

            messages.success(request, 'Обліковий запис успішно створено!')
            # Обработка успешной регистрации

            return JsonResponse(data={}, status=200)

        else:
            errors = form.errors.as_json()
            return JsonResponse(data={'errors': errors}, status=400)



class ProfileListView(ListView):
    model = Profile
    template_name = 'users/translators.html'
    context_object_name = 'translators'

    def get(self, request):
        order = request.GET.get('order_t', 'nick')

        translators = (Profile.objects.
            filter(group__name__startswith='Перекладач').
            annotate(total_books=Count('user__books')).
            annotate(total_chapters=Count('user__books__book_chapters')).
            annotate(author_avg_rating=Avg('user__books__book_ratings__stars')).
            annotate(free_chapters=Sum(
                Case(When(
                    user__books__book_chapters__price=0, then=1),
                    default=0, output_field=IntegerField(),
                    )))
        )

        if order == 'nick':
            translators = translators.order_by('username')
        if order == 'book_count':
            translators = translators.order_by('-total_books')
        if order == 'chapter_count':
            translators = translators.order_by('-total_chapters')
        if order == 'avg_rating':
            translators = translators.order_by('-author_avg_rating')
        if order == 'free_chapters':
            translators = translators.order_by('-free_chapters')
        if order == 'activity':
            translators = sorted(translators, key=Profile.total_activity, reverse=True)
        if order == 'last_login':
            translators = translators.order_by('-user__last_login')

        context = {
            'translators': translators, 'ordert': order
        }
        return render(request, 'users/translators.html', context)


# Для  користувача який онлайн
class ProfileDetail(LoginRequiredMixin, DetailView):
    """Вывод профиля пользователя"""
    model = Profile
    context_object_name = 'profile'
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        total_chars = sum(ch.content_length for ch in Chapter.objects.filter(book__user=self.request.user))

        user = (Profile.objects.filter(user=self.request.user).
            annotate(total_chapters=Count('user__books__book_chapters')).
            annotate(author_avg_rating=Avg('user__books__book_ratings__stars')).
            annotate(free_chapters=Sum(
                Case(When(
                    user__books__book_chapters__price=0, then=1),
                    default=0, output_field=IntegerField(),
                    ))))

        # Вычисляем комиссию на основе количества символов
        if total_chars < 5000:
            commission_rate = 15
        elif total_chars < 10000:
            commission_rate = 12
        else:
            commission_rate = 5

        context['user_profile'] = user
        context['transactions'] = Transaction.objects.filter(user=self.request.user)
        context['total_chars'] = total_chars
        context['commission_rate'] = commission_rate

        return context



class OtherUserProfileDetail(DetailView):
    """Вывод профиля другого пользователя"""
    model = Profile
    context_object_name = 'profile'
    template_name = 'users/other_profile.html'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')  # Получаем имя пользователя из URL-параметра
        user = get_object_or_404(User, username=username)
        return user.profile

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    """Редактирование профиля"""
    form_class = ProfileForm
    model = Profile
    template_name = "users/profile_form.html"


    def form_valid(self, form):
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user.profile

    def form_invalid(self, form):
        print(form.instance.username)
        print(form.instance.email)
        print(form.instance.about)
        print(form.instance.image)
        return super().form_invalid(form)

    success_url = reverse_lazy('users:ProfileUpdate')




@login_required
@transaction.atomic
def add_funds(request):
    if request.method == 'POST':
        form = AddFundsForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            # тут ваш код для интеграции с платежной системой
            user_profile = UserProfile.objects.get(user=request.user)
            user_profile.balance += amount
            user_profile.save()

            # Записываем транзакцию
            Transaction.objects.create(user=request.user, amount=amount, description="Пополнение баланса")

            return redirect('profile_view')
    else:
        form = AddFundsForm()

    return render(request, 'users/add_funds.html', {'form': form})








def calculate_commission(amount, total_chars):
    if total_chars < 5000:
        commission_rate = 0.15
    elif total_chars < 10000:
        commission_rate = 0.12
    else:
        commission_rate = 0.05

    return amount * Decimal(commission_rate)




SYSTEM_USER_ID = 1  # ID системного пользователя
@login_required
@transaction.atomic
def purchase_chapter(request, chapter_id):
    profile = Profile.objects.get(user=request.user)
    chapter = get_object_or_404(Chapter, id=chapter_id)
    book = chapter.book



    if not book:
        messages.error(request, "Ошибка: глава не связана с книгой!")

        return redirect(request.META.get('HTTP_REFERER', 'default_redirect_url'))

    book_owner = book.user  # Получаем владельца книги
    price = chapter.price

    # Подсчет символов всех книг пользователя
    total_chars = sum(ch.content_length for ch in Chapter.objects.filter(book__user=book_owner))
    commission = calculate_commission(price, total_chars)

    if profile.balance >= price:

users/templates/users/add_funds.html
<h1>Пополнить баланс</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Пополнить">
</form>

users/templates/users/commission_stats.html
{% extends "base.html" %}


{% extends 'main/base.html'%}
{% block content %}
<h2>Статистика комиссий</h2>
<p>Общий баланс комиссий: {{ system_user_balance }}</p>
<h3>Детали транзакций</h3>
<table>
    <thead>
        <tr>
            <th>Дата</th>
            <th>Сумма</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
        {% for transaction in transactions %}
        <tr>
            <td>{{ transaction.date_created }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}



{% endblock %}

users/templates/users/dialogs_list.html
{% extends 'main/base.html'%}

{% block content %}
  {% for dialog in dialogs %}
    {% if dialog.user1 == request.user %}
      <a href="{% url 'users:dialog_view' dialog.id %}">{{ dialog.user2.username }}</a>
    {% else %}
      <a href="{% url 'users:dialog_view' dialog.id %}">{{ dialog.user1.username }}</a>
    {% endif %}
  {% endfor %}
{% endblock %}

users/templates/users/login_modal.html
{% load static %}





<div class="login-modal" id="login-modal"  style="z-index:100" xmlns="http://www.w3.org/1999/html">
    <div class="modal-content">
        <h2>Login</h2>
           <form class="SignInModal_modalContainer__oNXTr" id="login-form" method="post" action="{% url 'users:login_modal' %}">
                {% csrf_token %}
                        <img id="close-login" alt="close modal"  src="{% static 'main/image/icons/closeIcon.e48e8df6.svg' %}" width="24" height="24" decoding="async" data-nimg="1" class="SignInModal_closeIcon__5eMYF" loading="lazy" style="color: transparent;" />
                                            <script>
                                            // Создайте функцию для закрытия модального окна
                                            function closeModal() {
                                              // Получите ссылку на модальное окно
                                              const modal = document.querySelector(".Modal_modal__2Ms_4");

                                              // Скрыть или удалить модальное окно (в зависимости от вашей реализации)
                                              modal.style.display = "none"; // Пример для скрытия модального окна

                                              // Дополнительные действия для закрытия модального окна, если необходимо
                                            }

                                            // Получите ссылку на элемент изображения
                                            const closeIcon = document.getElementById("close-login");

                                            // Добавьте обработчик события клика
                                            closeIcon.addEventListener("click", function() {
                                              // Вызовите функцию для закрытия модального окна
                                              closeModal();
                                            });
                                            </script>

                <div class="mb-3 mt-md-4">

                    <p class="mb-5 text-center">З поверненням!</p>
                    <div class="form-floating mb-3">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <div class="SignInModal_forgetPasswordText__wxuUy">Забули пароль?</div>
                <div>
                    <p class="mb-0 text-center">
                        Ще не зареєструвалися??
                        <a href="{% url 'users:signup_modal' %}" class="text-primary fw-bold">Створіть акаунт</a>
                    </p>
                </div>

                <div class="SignInModal_submitBtnContainer__PMCuy" class="col-12 d-grid"><button class="col-12 d-grid"  type="submit">Увійти</button></div>
                <div class="SignInModal_orDividerContainer__qyGQZ">
                    <div class="Divider_divider__JVzFi"></div>
                    <div>або</div>
                    <div class="Divider_divider__JVzFi"></div>
                </div>
                <div class="SignInModal_buttonsContainer__gBknw">
                    <button class="Button_button__N5rM1" type="button">
                        <img alt="Facebook icon" src="{% static 'main/image/icons/facebookIcon.a80d0756.svg' %}" width="24" height="24" decoding="async" data-nimg="1" loading="lazy" style="color: transparent;" />Facebook
                    </button>
                    <button class="Button_button__N5rM1" type="button">
                        <img alt="Google icon" src="{% static 'main/image/icons/googleIcon.96cc987b.svg' %}" width="24" height="24" decoding="async" data-nimg="1" loading="lazy" style="color: transparent;" />Google
                    </button>
                </div>
           </form>
    </div>
</div>

<script>

</script>





<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        console.log('JS code is running');
        $('#login-form').on('submit', function(e) {
            e.preventDefault();

            console.log('Request sent to server');

            $.ajax({
                url: '{% url "users:login_modal" %}',
                method: 'POST',
                data: $(this).serialize(),
                success: function(data) {
                    console.log(data);
                    if (data.access) {
                        // Сохраните токен в локальном хранилище
                        localStorage.setItem('jwt_token', data.access);

                        // Отправить токен на сервер Python
                        sendTokenToServer(data.access);

                        // Выведите токен в консоль браузера
                        console.log('Token:', data.access);

                        // Далее выполните действия после успешной аутентификации
                        window.location.href = '{% url "main:home" %}';
                    } else {
                        // Обработка ошибки аутентификации, если необходимо
                        console.error('Ошибка аутентификации');
                    }
                },
                error: function() {
                    console.error('Ошибка при запросе аутентификации');
                }
            });
        });

        // Функция для отправки токена на сервер Python
        function sendTokenToServer(token) {
            $.ajax({
                url: '{% url "users:save_token" %}',
                method: 'POST',
                data: { 'token': token },
                success: function(response) {
                    console.log('Токен успешно отправлен на сервер');
                },
                error: function() {
                    console.error('Ошибка при отправке токена на сервер');
                }
            });
        }
    });
</script>

users/templates/users/other_profile.html
{% extends 'main/base.html'%}
{% load static %}
{% load custom_tags %}


{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home'%}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'users:profile' %}"><p>Профіль</p></a>
        </div>
        <div class="main_page_title">
          <h2>Профіль</h2>
        </div>
        <div class="settings_content">
          <div class="user_login">
            <p class="login_text">Логін:</p>
            <p class="login_name">{{ profile.username }}</p>
          </div>
          <div class="user_about_content">
            <div class="user_about_img" >
              <img src="{{ profile.image.url }}" alt="profile" width="25%" height="50%" />
            </div>
            <div class="user_about_desc">
              <div class="user_about_desc_item">
                <div>
                  <p>Про себе:</p>
                </div>
                <div>
                  <p>{{ profile.about|truncatechars:400  }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Тип профілю:</p>
                </div>
                <div>
                  <p>{{ user.profile.group.name }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Загальна кількість перекладених символів:</p>
                </div>
                <div>
                  <p>{{ total_chars }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Загальна кількість розділів:</p>
                </div>
                <div>
                  <p>{{ user }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Загальна кількість безкоштовних розділів:</p>
                </div>
                <div>
                  <p>{{ user }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Середній рейтинг перекладів:</p>
                </div>
                <div>
                  <p>{{ user }}</p>
                </div>
              </div>
              <div class="user_about_desc_item">
                <div>
                  <p>Загальна активність в книгах:</p>
                </div>
                <div>
                  <p>{{ user }}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="user_settings_other">
            <div class="user_settings_btns">
              <a href="#" class="send_sms">Написати повідомлення</a>
            </div>
          </div>

        </div>
      </div>

{% endblock %}

users/templates/users/profile_list.html
{% extends 'main/base.html'%}
{% block content %}
  <h1>Список профилей</h1>
  <ul>
    {% for profile in profiles %}
      <li>
        <a href="{% url 'users:other_profile_detail' username=profile.user.username %}">
          {{ profile.user.username }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

users/templates/users/signup_modal.html
<div class="modal-content">
    <h2>Register</h2>
    <form id="signup-form" method="post" action="{% url 'users:signup_modal' %}">
        {% csrf_token %}

        <!-- Добавляем скрытое поле с именем 'next' и значением '{{ page }}' -->
        <input type="hidden" name="next" value="{{ page }}">

        <div class="mb-3 mt-md-4">
            <p class="mb-5 text-center">Вітаємо на сайті!!!</p>
            <div class="form-floating mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-floating mb-3">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="form-floating mb-3">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>

            <div class="col-12 d-grid">
                <button class="btn btn-primary rounded-pill" type="submit">Створити акаунт</button>
            </div>
        </div>
        <div>
            <p class="mb-0 text-center">
                Вже маєте акаунт?
                <a href="{% url 'users:login_modal' %}" class="text-primary fw-bold">Увійдіть на сайт</a>
            </p>
        </div>
        <button id="close-register">Закрыть</button>
    </form>
</div>

users/templates/users/translators.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'users:translators' %}"><p>Перекладачі</p></a>
        </div>
        <div class="main_page_title">
          <h2>Перекладачі</h2>
        </div>
        <div class="translator_top_actions main_bb">
          <p>Показано {{translators.count }} перекладачів</p>
          <div class="translator_filter">
            <span>Сортувати</span>
            <form action="" method="get" id="sortformt">
              <input type="hidden" id="ordervalt" value="{{ordert}}">
              <select name="order_t" id="order_t" onchange="sendSortT()">
                <option id="nick" value="nick">никнейм</option>
                <option id="book_count" value="book_count">кількість книг</option>
                <option id="chapter_count" value="chapter_count">кількість розділів</option>
                <option id="avg_rating" value="avg_rating">cередній рейтинг перекладів</option>
                <option id="free_chapters" value="free_chapters">кількість безкоштовних розділів</option>
                <option id="activity" value="activity">активність</option>
                <option id="last_login" value="last_login">останнє відвідування</option>
              </select>
            </form>
          </div>
        </div>

        <script>
          function sendSortT() {
            var form = document.getElementById('sortformt');
            form.submit();
          };

          $(document).ready(function () {
            var sel = document.getElementById('ordervalt');
            var opt = document.getElementById(sel.value)
            $('#'+sel.value).attr("selected", "selected");
          });
        </script>


        <table class="translator_table">
          <thead>
            <tr>
              <td>Никнейм</td>
              <td>Кількість книг</td>
              <td>Кількість розділів</td>
              <td>Середній рейтинг перекладів</td>
              <td>Кількість безкоштовних розділів</td>
              <td>Активність</td>
              <td>Останнє відвідування</td>
            </tr>
          </thead>
          <tbody>
            {% for translator in translators %}
            <tr class="main_bb">
              <td>{{ translator.username }}</td>
              <td>{{ translator.user.books.count }}</td>
              <td>{{ translator.total_chapters }}</td>
              {% if translator.author_avg_rating == None %}
                <td>0</td>
              {% else %}
                <td>{{ translator.author_avg_rating|floatformat }}</td>
              {% endif %}
              <td>{{ translator.free_chapters }}</td>
              <td>{{ translator.total_activity }}</td>
              <td>{{ translator.user.last_login|date:"d.m.Y" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        {% include 'include/show_more.html' %}
      </div>

{% endblock %}