FanVers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('Advertisement/', include(('Advertisement.urls', 'Advertisement'), namespace='Advertisement')),
    path('ckeditor/', include('ckeditor_uploader.urls')), #текстовый редактор CKEditor
    re_path(r'^public/(?P<path>.*)$', serve, {'document_root': settings.BASE_DIR / 'public'}), #временное отображение папки public

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "main.views.page_not_found_view"

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('For-copyright-holders/', views.For_copyright_holders, name='For_copyright_holders'),
    path('user-agreement/', views.user_agreement, name='user_agreement'),
    path('Reference/', views.Reference, name='Reference'),
    path('Write-to-support/', views.Write_to_support, name='Write_to_support'),
    path('Contacts/', views.Contacts, name='Contacts'),
    path('money_problem/', views.money_problem, name='money_problem'),
    path('Suggest_improvements/', views.Suggest_improvements, name='Suggest_improvements'),
    path('thanks/', views.thanks, name='thanks'),
    path('FAQ/', views.faq, name='faq'),
    path("__debug__/", include("debug_toolbar.urls")),
]

handler404 = "main.views.page_not_found_view"

main/models.py
from django.db import models

class Settings(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from catalog.models import Book
from .models import Settings
from Advertisement.models import *
from Advertisement.views import del_adv
from catalog.serializers import BookSerializer
from django.views.generic import ListView, TemplateView
from datetime import date, timedelta
from django.utils import timezone
from django.db.models import Count

class HomePageView(ListView):
    model = Book
    serializer_class = BookSerializer
    template_name = 'main/index.html'

    def adv_show(self):
        del_adv()
        adv = Advertisement.objects.filter(location='main')
        adv_books = list()
        for book in adv:
            adv_books.append(book.book_id)

        adv_books = Book.objects.filter(id__in=adv_books)

        return adv_books

    def new_books(self):
        end_of_month = timezone.now()
        start_of_month = end_of_month - timezone.timedelta(days=30)
        new_books = Book.objects.filter(
        pub_date__range=(start_of_month, end_of_month)
        ).order_by('-pub_date')[:8]
        return new_books

    def last_updated_books(self):
        end_of_month = timezone.now()
        start_of_month = end_of_month - timezone.timedelta(days=30)
        last_updated_books = Book.objects.filter(
        book_chapters__created_at__range=(start_of_month, end_of_month)
        ).distinct().order_by('-book_chapters__created_at')[:6]
        return last_updated_books

    def trending_books(self):
        trending_books = Book.objects.order_by('-trending_score')[:6]
        return trending_books

    def top_day_books(self):
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=1)

        top_day_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_day_books

    def top_week_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=7)

        top_week_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_week_books

    def top_month_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=30)

        top_month_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_month_books

    def top_general_books(self):
        # Визначте початок і кінець останнього дня
        end_of_day = timezone.now()
        start_of_day = end_of_day - timezone.timedelta(days=365)

        top_general_books = (
            Book.objects
            .annotate(num_ratings=Count('book_ratings'))
            .filter(book_ratings__timestamp__range=(start_of_day, end_of_day))
            .order_by('-num_ratings') # Отримати топ-6 книг
        )[:6]
        return top_general_books



def For_copyright_holders(request):
    return render(request, 'main/For_copyright_holders.html')

def Reference(request):
    return render(request, 'main/Reference.html')

def Write_to_support(request):
    return render(request, 'main/Write_to_support.html')
def Contacts(request):
    return render(request, 'main/Contacts.html')

def thanks(request):
    return render(request, 'main/thanks.html')

def Suggest_improvements(request):
    return render(request, 'main/Suggest_improvements.html')

def money_problem(request):
    return render(request, 'main/money_problem.html')
def user_agreement(request):
    return render(request, 'main/user_agreement.html')

def faq(request):
    return render(request, 'main/faq.html')

def page_not_found_view(request, exception):
    return render(request, 'main/404.html', status=404)

main/templates/main/Contacts.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:Contacts' %}"><p>Контакти</p></a>
        </div>
        <div class="main_page_title">
          <h2>Контакти</h2>
           <h4> <p>

Пошта: FanVers.com<p>

ПІП: Криворучко Світлана Миколаївна<p>

Адресв: ------------<p>
</h4>

        </div>


{% endblock %}

main/templates/main/For_copyright_holders.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}

    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:user_agreement' %}"><p>Для правовласників</p></a>
        </div>
        <div class="main_page_title">
          <h2>Для правовласників</h2>
        </div>

        <div class="faq_content">



Проект «FanVers.com»
Ми спільнота прихильників новел, ранобе та книг, де користувачі мають можливість розміщувати власні переклади та свої власні твори. Також користувачі мають можливість отримувати доступ та ділитися творами з іншими учасниками спільноти.

Захист авторських прав згідно з:
•	Законодавством України :
1.	Про веб-сайт як об'єкт авторського права [Електронний ресурс] // Лист Державного департаменту інтелектуальної власності, Міністерство освіти і 202 науки України N 16-14/231 від 22.01.2007. – 2007. –
2.	Щодо об'єктів авторського права [Електронний ресурс] // Лист Державного департаменту інтелектуальної власності N 16-13/4470 від 05.08.2009. – 2009.
3.	Про деякі питання практики вирішення спорів, пов'язаних із захистом прав інтелектуальної власності [Електронний ресурс] // Постанова пленуму Вищого Господарського Суду України від 17.10.2012 № 12. – 2012
4.	Закон СРСР "Про пресу та інші засоби масової інформації" від 12.06.1990 № 1552-I // Відомості Верховної Ради України (ВВР), 1990, N 26, ст. 492.
•	Міжнародним законодавством:
1.	Всесвітня Конвенція про авторське право. [Електронний ресурс] // Міжурядова конференція з авторского права, Женева.
2.	Directive 2000/31/EC of the European Parliament and of the Council of 8 June 2000 on certain legal aspects of information society services, in particular electronic commerce, in the Internal Market ('Directive on electronic commerce') // OJ L 178, 17.7.2000, p. 1–16.


Ми дотримуємося Закону про захист авторських прав у цифровій епохі (DMCA) та інших чинних законів, що регулюють авторські права. Якщо ми отримаємо відповідне повідомлення про порушення прав, незаконно розміщені переклади будуть негайно видалені.

Повідомлення про порушення авторських прав.

Якщо ви вважаєте, що ваші авторські права порушено на сайті FanVers.com, ви можете надіслати повідомлення про порушення прав на електронну адресу FanVers@gmail.com. Згідно з частиною 512(c) Акту про авторські права (Digital Millennium Copyright Act), який висуває певні вимоги до форми цього повідомлення, слід обов’язково надати таку інформацію:

1.	Ваш підпис або електронний підпис особи, яка представляє вас чи особу, чиї авторські права були порушені.

2.	Вказівку на роботи (матеріали), щодо яких порушено права, разом з посиланнями(URL)  на кожен з них. У разі, коли повідомлення повідомляє про порушення авторського права на кілька таких матеріалів (текстів, зображень), у ньому мають бути наведені вказівки на кожен із них.







3.	Вказівку на матеріал, який порушує авторські права або є предметом порушення, і зазначення, який саме матеріал потрібно видалити чи заблокувати, а також посилання на вихідну адресу цього матеріалу.

4.	Ваші ім’я та прізвище, контактні дані, включаючи адресу електронної пошти, поштову адресу та номер телефону.

5.	Підтвердження вашої впевненості, що використання матеріалу порушує авторські права і не дозволяється власником авторських прав, агентом чи законодавством.

6.	Заява, що надана вами інформація є правдивою і точною, і ви розумієте можливі наслідки надання неправдивої інформації


Далі в інструкції сказано, що адміністратор сайту або особа, яка розмістила спірний матеріал, має право подати зустрічну скаргу відповідно до 512(g)(2) та 512(g)(3) Закону США «Про авторське право в цифрову епоху» [47].


Видалення або блокування доступу до матеріалу.

Після отримання повідомлення про порушення авторських прав, «FanVers.com» вживає заходів щодо видалення чи блокування спірних матеріалів протягом 7 робочих днів. Якщо інформація недостатня або виникають сумніви, ми можемо зв'язатися з вами для отримання додаткової інформації.

В разі багаторазових порушень авторських прав власники акаунтів на «FanVers.com»  можуть втратити доступ до сервісу відповідно до наших правил.

Зустрічне повідомлення.

Якщо ви не згодні із блокуванням вашого перекладу і вважаєте себе власником прав на нього, ви можете надіслати зустрічне повідомлення за адресою FanVers@gmail.com. Після розгляду вашого повідомлення доступ до вашого перекладу може бути відновлений.

Зверніть увагу, що подавши неправдиву інформацію, ви можете бути притягнуті до відповідальності згідно з частиною 512(f) Актом про авторські права.



  </div>
      </div>



{% endblock %}

main/templates/main/Reference.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:Reference' %}"><p>Reference</p></a>
        </div>
        <div class="main_page_title">
          <h2>Довідка</h2>
        </div>

        <div class="faq_content">
          <h2>Як користуватись сайтом</h2>
          <a href="#">Як створити переклад на сайті UAlate.com </a>
          <a href="#">Налаштування перекладу</a>
          <a href="#">Теги / жанри / фендоми </a>
          <a href="#">Як створити перший розділ у перекладі </a>
          <a href="#">Реклама вашого перекладу на сайті </a>
          <a href="#">Як поповнити баланс </a>
          <a href="#">Як знайти цікаву розповідь </a>
          <a href="#">Помилки у тексті </a>
          <a href="#"> Коментарі </a>
        </div>
      </div>

{% endblock %}

main/templates/main/Suggest_improvements.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:Suggest_improvements' %}"><p>Запропонувати покращення</p></a>
        </div>
        <div class="main_page_title">
          <h2>Запропонувати покращення</h2>

        </div>


{% endblock %}

main/templates/main/Write_to_support.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:Write_to_support' %}"><p>Написати у підтримку</p></a>
        </div>
        <div class="main_page_title">
          <h2>Довідка</h2>
        </div>


{% endblock %}

main/templates/main/faq.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:faq' %}"><p>FAQ</p></a>
        </div>
        <div class="main_page_title">
          <h2>FAQ</h2>
        </div>

        <div class="faq_content">
          <h2>Як користуватись сайтом</h2>
          <a href="#">Як створити переклад на сайті UAlate.com </a>
          <a href="#">Налаштування перекладу</a>
          <a href="#">Теги / жанри / фендоми </a>
          <a href="#">Як створити перший розділ у перекладі </a>
          <a href="#">Реклама вашого перекладу на сайті </a>
          <a href="#">Як поповнити баланс </a>
          <a href="#">Як знайти цікаву розповідь </a>
          <a href="#">Помилки у тексті </a>
          <a href="#"> Коментарі </a>
        </div>
      </div>

{% endblock %}

main/templates/main/money_problem.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:money_problem' %}"><p>Не поповнився баланс</p></a>
        </div>
        <div class="main_page_title">
          <h2>Не поповнився баланс?</h2>

        </div>


{% endblock %}

main/templates/main/pagination.html
{% if queryset.has_other_pages %}
    <div class="text-center">
        <ul class="list-unstyled list-inline my-2">
            {% if queryset.has_previous %}
                <li class="list-inline-item">
                    <a href="?page={{ queryset.previous_page_number }}"
                       class="btn page-link"
                       data-page="{{ queryset.previous_page_number }}">&#10094; Попередня</a>
                </li>
            {% endif %}
            {% for page in custom_range %}
                {% if page == queryset.number %}
                    <li class="list-inline-item">
                        <a href="?page={{ page }}" class="btn page-link" data-page="{{ page }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="list-inline-item">
                        <a href="?page={{ page }}" class="btn page-link" data-page="{{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if queryset.has_next %}
                <li class="list-inline-item">
                    <a href="?page={{ queryset.next_page_number }}"
                       class="btn page-link"
                       data-page="{{ queryset.next_page_number }}">Наступна &#10095;</a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

main/templates/main/thanks.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'main:thanks' %}"><p>Сказати «дякую!»</p></a>
        </div>
        <div class="main_page_title">
          <h2>Сказати «дякую!»</h2>

        </div>


{% endblock %}