FanVers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('Advertisement/', include(('Advertisement.urls', 'Advertisement'), namespace='Advertisement')),
    path('ckeditor/', include('ckeditor_uploader.urls')), #текстовый редактор CKEditor
    re_path(r'^public/(?P<path>.*)$', serve, {'document_root': settings.BASE_DIR / 'public'}), #временное отображение папки public

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "main.views.page_not_found_view"

catalog/urls.py
from django.urls import path, include
from .views import book_create, edit_chapter, setting_book,  TitleAutocompleteView,   GenresAutocompleteView, TagsAutocompleteView, FandomAutocompleteView, BookAdultAutocompleteView, BookNotAdultAutocompleteView
from .forms import TagAutocomplete, FandomAutocomplete, CountryAutocomplete, GenresAutocomplete
from .views import (
    Catalog, BookBase, TagList, TagDetail, GenresList, GenresDetail, FandomList, FandomDetail, CountryList, CountryDetail, ChapterCreate, ChapterDetail)
from .views import become_translator, become_freelancer
from .views import change_group, NotificationListAPIView, BookSearchView, BookmarkActionView
from . import views
from .views import *
from django.http import HttpResponse

app_name = 'catalog'

urlpatterns = [
    path('', Catalog.as_view(), name='catalog'),
    path('search/', BookSearchView.as_view(), name='search'),
    path('search_results/', Search.as_view(), name='search_results'),
    path('books/new/', book_create, name='book_create'),
    path('book/<slug:book_slug_setting_book>/adv/', book_advertisement_settings, name='book_advertisement_settings'),
    path('book/<slug:book_slug_setting_book>/ajax_cost/', ajax_cost, name='ajax_cost'),
    path('book/<slug:book_slug_setting_book>/ajax_cost_sum/', ajax_cost_sum, name='ajax_cost_sum'),
    path('book/<slug:book_slug>/create_chapter/', ChapterCreate.as_view(), name='create_chapter'),
    path('book/<slug:book_slug>/<slug:chapter_slug>/', ChapterDetail.as_view(), name='chapter_detail'),
    path('book/<slug:book_slug>/<slug:chapter_slug>/edit/', edit_chapter, name='chapter_edit'),
    path('tags-autocomplete/', TagAutocomplete.as_view(), name='tags-autocomplete'),
    path('fandoms-autocomplete/', FandomAutocomplete.as_view(), name='fandoms-autocomplete'),
    path('country-autocomplete/', CountryAutocomplete.as_view(), name='country-autocomplete'),
    path('genres-autocomplete/', GenresAutocomplete.as_view(), name='genres-autocomplete'),
    path('book/<slug:slug>/', BookBase.as_view(), name='Book_Base'),
    path('book/<slug:book_slug_setting_book>', setting_book, name='setting_book'),
    path('tags/', TagList.as_view(), name='tag_list'),
    path('tags/<int:pk>/', TagDetail.as_view(), name='tag_detail'),
    path('fandoms/', FandomList.as_view(), name='fandom_list'),
    path('fandoms/<int:pk>/', FandomDetail.as_view(), name='fandom_detail'),
    path('genres/', GenresList.as_view(), name='genres_list'),
    path('genres/<int:pk>/', GenresDetail.as_view(), name='genres_detail'),
    path('countries/', CountryList.as_view(), name='country_list'),
    path('countries/<int:pk>/', CountryDetail.as_view(), name='country_detail'),
    path('change_group/<str:new_group_name>/', change_group, name='change_group'),
    path('become_translator/', become_translator, name='become_translator'),
    path('become_freelancer/', become_freelancer, name='become_freelancer'),
    path('like_comment/<int:comment_id>/', views.LikeCommentView.as_view(), name="like_comment"),
    path('dislike_comment/<int:comment_id>/', views.DislikeCommentView.as_view(), name="dislike_comment"),
    path('delete_comment/<int:comment_id>/', views.DeleteCommentView.as_view(), name="delete_comment"),
    path('rate_book/', views.rate_book, name='rate_book'),
    path('get_user_rating', views.get_user_rating, name='get_user_rating'),
    path('quality_translation/', views.quality_translation, name='quality_translation'),
    path('get_user_quality/', views.get_user_quality, name='get_user_quality'),
    path('ajax/autocomplete/title/', TitleAutocompleteView.as_view(), name='title_autocomplete'),
    path('ajax/autocomplete/genres/', GenresAutocompleteView.as_view(), name='genres_autocomplete'),
    path('ajax/autocomplete/tags/', TagsAutocompleteView.as_view(), name='tags_autocomplete'),
    path('ajax/autocomplete/fandom/', FandomAutocompleteView.as_view(), name='fandom_autocomplete'),
    path('ajax/autocomplete/adult/', BookAdultAutocompleteView.as_view(), name='book_adult_autocomplete'),
    path('ajax/autocomplete/not-adult/', BookNotAdultAutocompleteView.as_view(), name='book_not_adult_autocomplete'),
    path('get_additional_data/', views.get_additional_data, name='get_additional_data'),
    path('api/notifications/', NotificationListAPIView.as_view(), name='notification-list'),
    path('notifications/', NotificationListView.as_view(), name='notification-lists'),
    path('catalog/book/<slug:slug>/bookmark/', BookmarkActionView.as_view(), name='bookmark_action'),
    path('catalog/bookmarks/', BookmarkListView.as_view(), name='bookmarks'),
    path('catalog/bookmarks/all/', get_bookmarks_all, name='all'),
    path('catalog/bookmarks/read/', get_bookmarks_read, name='read'),
    path('catalog/bookmarks/special/', get_bookmarks_special, name='special'),
    path('catalog/bookmarks/in_plans/', get_bookmarks_in_plans, name='in_plans'),
    path('catalog/bookmarks/left/', get_bookmarks_left, name='left'),
    path('catalog/bookmarks/end_read/', get_bookmarks_end_read, name='end_read'),
    path('catalog/mytranslations/', OwnTranslationsListView.as_view(), name='own-translations'),
    path('catalog/left_translations/', LeftTranslationsListView.as_view(), name='left-translations'),
]

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('For-copyright-holders/', views.For_copyright_holders, name='For_copyright_holders'),
    path('user-agreement/', views.user_agreement, name='user_agreement'),
    path('Reference/', views.Reference, name='Reference'),
    path('Write-to-support/', views.Write_to_support, name='Write_to_support'),
    path('Contacts/', views.Contacts, name='Contacts'),
    path('money_problem/', views.money_problem, name='money_problem'),
    path('Suggest_improvements/', views.Suggest_improvements, name='Suggest_improvements'),
    path('thanks/', views.thanks, name='thanks'),
    path('FAQ/', views.faq, name='faq'),
    path("__debug__/", include("debug_toolbar.urls")),
]

handler404 = "main.views.page_not_found_view"

catalog/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from .models import Book, Tag, Fandom, Country, Genres, Chapter, Comment, Like, Dislike, Rating, Quality, Income, ViewedBooks, ViewedChapters
from .forms import BookForm, ChapterForm, CommentForm
from .forms import EditBookForm
from Advertisement.models import Advertisement
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from users.models import Profile, Bookmark
import logging
from django.contrib.contenttypes.models import ContentType
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.views import View
from django.db.models import Count, Sum
from django.http import JsonResponse, HttpResponseForbidden
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest
from django_filters.rest_framework import DjangoFilterBackend
from .serializers import BookSerializer
from rest_framework import generics
from .filters import BookFilter
from django_filters.widgets import BooleanWidget
import django_filters
from rest_framework.renderers import TemplateHTMLRenderer
from django.db.models import Q, F
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from .models import Notification
from .serializers import NotificationSerializer, FandomSerializer
from datetime import date, datetime
import requests
from rest_framework.decorators import api_view
from django.conf import settings
from django.db import transaction
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from Advertisement.models import Advertisement

class Catalog(ListView):
    model = Book
    template_name = 'catalog/catalog.html'
    context_object_name = 'books'

    def get(self, request):
        genres = Genres.objects.all().values('name', 'id')
        tags = Tag.objects.all().values('name', 'id')
        fandoms = Fandom.objects.all().values('name', 'id')
        order = request.GET.get('order', 'title')

        if request.GET.getlist('bookid'):
            books = request.GET.getlist('bookid')
            books = Book.objects.filter(id__in=books)
        else:
            books = Book.objects.all()

        books = book_filter(self.request, books, order)

        content = {
            'books': books, 'genres': genres, 'tags': tags,
            'fandoms': fandoms, 'order': order
        }
        return render(request, 'catalog/catalog.html', content)

    def adv_show(self):
        Advertisement.objects.filter(end_date__lt=date.today()).delete()
        adv = Advertisement.objects.filter(location='catalog')
        adv_books = list()
        for book in adv:
            adv_books.append(book.book_id)

        listbooks = Book.objects.filter(id__in=adv_books)

        return listbooks

class BookBase(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/about.html'

    def get(self, request, slug):
        book = get_object_or_404(Book, slug=slug)

        book_views = ViewedBooks.objects.update_or_create(book=book, user=request.user)

        today = timezone.now().date()
        comment_form = CommentForm()

        translator_books = Book.objects.filter(user=book.user)[:8]

        chapters = Chapter.objects.filter(book=book.id).order_by('created_at')

        comments = Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(book), object_id=book.id,
        parent__isnull=True).annotate(likes_count=Count('likes'
        ), dislikes_count=Count('dislikes')).order_by('-published')

        comments_reply = Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(book), object_id=book.id,
        parent__isnull=False).annotate(likes_count=Count('likes'
        ), dislikes_count=Count('dislikes')).order_by('-published')

        us = request.user

        context = {
        'slug': book.slug, 'book': book, 'translator_books': translator_books,
        'chapters':chapters, 'comments': comments,
        'comments_reply': comments_reply, 'today': today,
        'comment_form': comment_form, 'us': us
        }
        if book.user != request.user:
            return render(request, 'catalog/about.html', context)
        else:
            return render(request, 'catalog/admin-about-book.html', context)


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if request.POST.get("parent"):
                comment.parent_id = int(request.POST.get("parent"))
            comment.content_type = ContentType.objects.get_for_model(self.object)
            comment.object_id = self.object.id
            comment.owner = request.user
            likes_count = 0
            dislikes_count = 0
            comment.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse(
                    {'text': comment.text, 'id': comment.id,
                     'owner': comment.owner.username,
                     'likes_count': likes_count,
                     'dislikes_count': dislikes_count,
                     'parentid': comment.parent_id
                     })  # Возвращаем JSON
            messages.success(request, 'Ваш комментарий появится после проверки модератором')
            return redirect('catalog:Book_Base', slug=self.object.slug)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'error': form.errors}, status=400)

class BookmarkListView(ListView):
    model = Bookmark
    context_object_name = 'bookmarks'
    template_name = 'catalog/bookmarks.html'

    def get(self, request):
        bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id)
        return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_all(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id)
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_read(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id).filter(group='READ')
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_special(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id).filter(group='SPECIAL')
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_in_plans(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id).filter(group='IN_PLANS')
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_left(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id).filter(group='LEFT')
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

def get_bookmarks_end_read(request):
    bookmarks = Bookmark.objects.filter(user_profile_id=request.user.id).filter(group='END_READ')
    return render(request, 'catalog/bookmarks.html', {'bookmarks': bookmarks})

@method_decorator(require_POST, name='post')
class BookmarkActionView(View):
    def post(self, request, slug):
        user = request.user
        new_group = request.POST.get('group')

        print('User:', user)  # Печатаем пользователя для отладки
        print('New Group:', new_group)  # Печатаем новую группу для отладки

        # Находим книгу по slug
        book = Book.objects.get(slug=slug)

        print('Book:', book)  # Печатаем найденную книгу для отладки

        # Проверяем, существует ли уже запись Bookmark для этого пользователя и книги
        bookmark, created = Bookmark.objects.get_or_create(user_profile=user.profile, book=book)

        print('Bookmark:', bookmark)  # Печатаем объект закладки для отладки

        # Обновляем значение группы
        if new_group:
            bookmark.group = new_group
        bookmark.save()

        print('Bookmark Group Updated:', bookmark.group)  # Печатаем обновленную группу для отладки

        # Возвращаем JSON-ответ
        # return JsonResponse({'success': True})
        return redirect('catalog:Book_Base', slug=book.slug)

@method_decorator(login_required, name='dispatch')
class LikeCommentView(View):
    def post(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        like, created = Like.objects.update_or_create(user=request.user, comment=comment)

        if not created:
            like.delete()

        dislike = Dislike.objects.filter(user=request.user, comment=comment).first()
        if dislike:
            dislike.delete()

        return JsonResponse({'likes': comment.likes.count(), 'dislikes': comment.dislikes.count()})


@method_decorator(login_required, name='dispatch')
class DislikeCommentView(View):
    def post(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        dislike, created = Dislike.objects.update_or_create(user=request.user, comment=comment)

        if not created:
            dislike.delete()

        like = Like.objects.filter(user=request.user, comment=comment).first()
        if like:

catalog/templates/catalog/bookmarks.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'catalog:bookmarks' %}"><p>Закладки</p></a>
        </div>
        <div class="main_page_title">
          <h2>Закладки</h2>
        </div>

        <div class="catalogue_content">
          <div class="catalogue_left">
            <div class="cat_sort translator_top_actions main_bb">
              <p>Показано {{ bookmarks.count }} книги</p>
              {% include 'include/sort.html' %}
            </div>
            <div class="cat_cards">
              {% for book in bookmarks %}
              <div class="cat_card bookmarks_card">
                <img src="{% static 'catalog/images/assets/images/harry.png' %}" alt="" />
                <p class="catalog_title">{{ book.book }}</p>
                <div class="item_status">
                  <p>NEW</p>
                </div>
              </div>
              {% endfor %}
            </div>
            <button class="about_book_action show_more">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
              >
                <path d="M14 15L10 19L14 23" stroke="white" />
                <path
                  d="M5.93782 15.5C5.14475 14.1264 4.84171 12.5241 5.07833 10.9557C5.31495 9.38734 6.07722 7.94581 7.24024 6.86729C8.40327 5.78877 9.8981 5.13721 11.4798 5.01935C13.0616 4.90149 14.6365 5.32432 15.9465 6.21856C17.2565 7.1128 18.224 8.42544 18.6905 9.94144C19.1569 11.4574 19.0947 13.0869 18.5139 14.5629C17.9332 16.0389 16.8684 17.2739 15.494 18.0656C14.1196 18.8573 12.517 19.1588 10.9489 18.9206"
                  stroke="white"
                  stroke-linecap="round"
                />
              </svg>
              <p>Показати ще</p>
            </button>
          </div>
          <div class="catalogue_right">
            <h3>Фільтри</h3>
            <a href="{% url 'catalog:all' %}">
            <div class="bookmarks_content">
              <div class="bookmarks_item">
                <p>Усі</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
              <a href="{% url 'catalog:read' %}">
              <div class="bookmarks_item">
                <p>Читаю</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
              <a href="{% url 'catalog:special' %}">
              <div class="bookmarks_item">
                <p>Обране</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
              <a href="{% url 'catalog:in_plans' %}">
              <div class="bookmarks_item">
                <p>У планах</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
              <a href="{% url 'catalog:left' %}">
              <div class="bookmarks_item">
                <p>Кинув</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
              <a href="{% url 'catalog:end_read' %}">
              <div class="bookmarks_item">
                <p>Прочитав</p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="8"
                  height="8"
                  viewBox="0 0 8 8"
                  fill="none"
                >
                  <circle cx="4" cy="4" r="4" fill="#00EAFD" />
                </svg>
              </div>
              </a>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

catalog/templates/catalog/chapter_edit.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    <div class="form-group">
        {{ form.title.label_tag }}
        {{ form.title }}
    </div>
    <div class="form-group">
        {{ form.content.label_tag }}
        {{ form.content }}
    </div>
    <div class="form-group">
        {{ form.file.label_tag }}Або можете завантажити файлом
        {{ form.file }}
    </div>


<script>

CKEDITOR.replace('editor', {

toolbar: [
'heading',
'|',
'bold',
'italic',
'link',
'bulletedList',
'numberedList',
'|',
'indent',
'outdent',
'|',
'blockQuote',
'insertTable',
'undo',
'redo'
],

config: {

default: {

  toolbar: [
    'heading',
    '|',
    'bold',
    'italic',
    'link',
    'bulletedList',
    'numberedList',
    '|',
    'indent',
    'outdent',
    '|',
    'blockQuote',
    'insertTable',
    'undo',
    'redo'
  ],

  height: 300,

  width: '100%',

  font_names: 'Times New Roman/Times New Roman;Arial/Arial, Helvetica, sans-serif;Verdana/Verdana, Geneva, sans-serif;Tahoma/Tahoma, Geneva, sans-serif;Webdings/Webdings;Symbol/Symbol;',

  font_defaultLabel: 'Tahoma',

  fontSize_sizes: '6/6px;8/8px;9/9px;10/10px;11/11px;12/12px;14/14px;16/16px;18/18px;20/20px;22/22px;24/24px;',

  fontColor: {

    colors: [
      'rgb(0, 0, 0)',
      'rgb(67, 67, 67)',
      'rgb(102, 102, 102)',
    ]

  }

}

}

});

</script>



    {{ form.price.label }}: {{ form.price }}





    <button type="submit">Загрузить</button>

</form>

{% endblock %}

catalog/templates/catalog/own-translations.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}
    <div class="page_wrapper main_page">

      <div class="main_content_wrapper">
        <div class="page_navigation">
          <a href="{% url 'main:home' %}"><p>Головна</p></a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 18 18"
            fill="none"
          >
            <path d="M6.75 4.5L11.25 9L6.75 13.5" stroke="white" />
          </svg>
          <a href="{% url 'catalog:own-translations' %}"><p>Власні переклади</p></a>
        </div>
        <div class="main_page_title">
          <h2>Власні переклади</h2>
        </div>

        <div class="catalogue_content own_translations_page">
          <div class="catalogue_left">
            <div class="cat_cards">
              {% for book in books %}
              <div class="cat_card">
                <a href="{% url 'catalog:Book_Base' book.slug %}">
                  <img src="{{ book.image.url }}" alt="" />
                </a>
                <div class="cat_card_desc">
                  <div>
                    <p>Дата створення</p>
                    <p>{{ book.pub_date|date:"d.m.Y" }}</p>
                  </div>
                  <div>
                    <p>Дата останньої активност</p>
                    <p>{{ book.last_updated|date:"d.m.Y" }}</p>
                  </div>
                  <div>
                    <p>Переглядів за день</p>
                    <p>{{ book.today_views }}</p>
                  </div>
                  <div>
                    <p>Загальна кількість переглядів</p>
                    <p>{{ book.viewed_by.count }}</p>
                  </div>
                  <div>
                    <p>Дохід за день</p>
                    <p>
                      {% if book.today_book_income == None %}
                        0$
                      {% else %}
                        {{ book.today_book_income }}$
                      {% endif %}
                    </p>
                  </div>
                  <div>
                    <p>Загальний дохід</p>
                    <p>
                      {% if book.total_income == None %}
                        0$
                      {% else %}
                        {{book.total_income }}$
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <button class="about_book_action show_more">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
              >
                <path d="M14 15L10 19L14 23" stroke="white" />
                <path
                  d="M5.93782 15.5C5.14475 14.1264 4.84171 12.5241 5.07833 10.9557C5.31495 9.38734 6.07722 7.94581 7.24024 6.86729C8.40327 5.78877 9.8981 5.13721 11.4798 5.01935C13.0616 4.90149 14.6365 5.32432 15.9465 6.21856C17.2565 7.1128 18.224 8.42544 18.6905 9.94144C19.1569 11.4574 19.0947 13.0869 18.5139 14.5629C17.9332 16.0389 16.8684 17.2739 15.494 18.0656C14.1196 18.8573 12.517 19.1588 10.9489 18.9206"
                  stroke="white"
                  stroke-linecap="round"
                />
              </svg>
              <p>Показати ще</p>
            </button>
          </div>
          <div class="catalogue_right">
            <h3>Cтатистика діяльності</h3>
            <div class="own_stats">
              <div class="main_bb">
                <p>Перекладів</p>
                <span>{{ books.count }}</span>
              </div>
              <div class="main_bb">
                <p>Сторінок переведено</p>
                <span>{{ total_pages }}</span>
              </div>
              <div class="main_bb">
                <p>Символів переклав</p>
                <span>{{ total_chars }}</span>
              </div>
            </div>
            <div class="about_book_cost comission">
              <span>{{ commission_rate }}%</span>
              <p>Комісія</p>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

catalog/templates/catalog/search_results.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<div id="search-results">
    <ul>
      {% for book in view.get_queryset %}
        <li>
            <a href="{%  url 'catalog:Book_Base' slug=book.slug %}">
              <img src="media\logo.png" alt="Обложка книги">
            </a>
            <h2><a href="{%  url 'catalog:Book_Base' slug=book.slug %}">{{ book.title }}</a></h2>
            <p>{{ book.author }}</p>
            <p>{{ book.description }}</p>
        </li>
      {% endfor %}
    </ul>
</div>
{% endblock %}